
-- status

CREATE TABLE IF NOT EXISTS status (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(50) NOT NULL UNIQUE,
	name VARCHAR(50) NOT NULL,
	color_background VARCHAR(25) NOT NULL,
	color_text VARCHAR(25) NOT NULL
);

-- users

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	login VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	email VARCHAR(250) NOT NULL DEFAULT ''
);

-- crons

CREATE TABLE IF NOT EXISTS crons (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_trigger INTEGER NOT NULL,
	id_user INTEGER DEFAULT NULL,
	code VARCHAR(50) NOT NULL UNIQUE,
	name VARCHAR(50) NOT NULL,
	timer VARCHAR(50) NOT NULL,
	FOREIGN KEY(id_trigger) REFERENCES triggers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- controllers

CREATE TABLE IF NOT EXISTS controllers_functions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(50) NOT NULL UNIQUE,
	name VARCHAR(50) NOT NULL,
	icon VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS controllers_types (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_function INTEGER NOT NULL,
	code VARCHAR(50) NOT NULL UNIQUE,
	name VARCHAR(50) NOT NULL,
	icon VARCHAR(25) NOT NULL,
	FOREIGN KEY(id_function) REFERENCES controllers_functions(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS controllers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_status INTEGER NOT NULL,
	id_type INTEGER NOT NULL,
	id_user INTEGER DEFAULT NULL,
	name VARCHAR(50) NOT NULL,
	token VARCHAR(100) NOT NULL UNIQUE,
	FOREIGN KEY(id_status) REFERENCES status(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id_type) REFERENCES controllers_types(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
